## Numpy

In [1]:
import numpy as np

### Basics

In [2]:
# Creating an array

a = np.array([1, 2, 3], dtype="int8")
b = np.array([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]])

In [3]:
# Print an array
print(f"Array a:\n{a}")
print(f"Array b:\n{b}")

Array a:
[1 2 3]
Array b:
[[1. 2. 3.]
 [4. 5. 6.]]


In [4]:
# Dimensions of an array
print(f"Dimensions of array a: {a.ndim}")
print(f"Dimensions of array b: {b.ndim}")

Dimensions of array a: 1
Dimensions of array b: 2


In [5]:
# Get type and size
print("Array\tType\tSize(bytes)")
print(f"a\t{a.dtype}\t{a.nbytes}")
print(f"b\t{b.dtype}\t{b.nbytes}")

Array	Type	Size(bytes)
a	int8	3
b	float64	48


In [6]:
# Shape of an array
print(f"Shape of array a: {a.shape}")
print(f"Shape of array b: {b.shape}")

Shape of array a: (3,)
Shape of array b: (2, 3)


### Accessing/Changing Numpy Arrays

In [7]:
a = np.array([[1, 2, 3, 4, 5, 6, 7], [8, 9, 10, 11, 12, 13, 14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [8]:
# Get a specific element [r, c]
print(a[1, 5])  # Accessing 13
print(a[-1, -2])

13
13


In [9]:
# Get a specific row/col
print(a[0, :])
print(a[:, 0])

[1 2 3 4 5 6 7]
[1 8]


In [10]:
# Change at specific index
a[1, 5] = 20
print(a)
print()

a[:, 2] = 100
print(a)
print()

a[1, :] = 0
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]

[[  1   2 100   4   5   6   7]
 [  8   9 100  11  12  20  14]]

[[  1   2 100   4   5   6   7]
 [  0   0   0   0   0   0   0]]


### Initializing different types of arrays

In [11]:
# All zeros matrix
zeros = np.zeros((2, 3, 2))
print(zeros)

[[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]


In [12]:
# All ones matrix
ones = np.ones((2, 3, 4))
print(ones)

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


In [13]:
# Initialize any other number
matrix = np.full((2, 3), np.inf)
print(matrix)

print()

# Initialize the shape instantly
print(a)
new_a = np.full_like(a, 100)
print(new_a)

[[inf inf inf]
 [inf inf inf]]

[[  1   2 100   4   5   6   7]
 [  0   0   0   0   0   0   0]]
[[100 100 100 100 100 100 100]
 [100 100 100 100 100 100 100]]


In [14]:
# Matrix of random decimal numbers
rand_nums = np.random.rand(4, 3)
print(rand_nums)

[[0.32112365 0.73523554 0.04627873]
 [0.74659112 0.78441704 0.93086471]
 [0.44190377 0.91683291 0.79315305]
 [0.43341792 0.86305164 0.71671095]]


In [15]:
# Matrix of random integers
rand_ints = np.random.randint(1, 100, size=(3, 2))
print(rand_ints)

[[92 96]
 [52 32]
 [39 94]]


In [16]:
# Identity matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [17]:
# Repeat an array
arr = np.array([[1, 2, 3]])
rep1 = np.repeat(arr, 4, axis=0)
rep2 = np.repeat(arr, 4, axis=1)
print(rep1)
print(rep2)

[[1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]]
[[1 1 1 1 2 2 2 2 3 3 3 3]]


In [18]:
# Range of numbers
rang = np.arange(2, 10, dtype="float32")
print(rang)

[2. 3. 4. 5. 6. 7. 8. 9.]


### Copying arrays

In [19]:
# Problem with copying arrays like lists

a = np.array([1, 2, 3])
b = a
print("Before")
print(f"a: {a}")
print(f"b: {b}\n")

b[0] = 100
print("After")
print(f"a: {a}")
print(f"b: {b}\n")

# Problem occurs because both the variables point to the same location in memory

Before
a: [1 2 3]
b: [1 2 3]

After
a: [100   2   3]
b: [100   2   3]



In [20]:
# Copying the right way
a = np.array([1, 2, 3])
b = a.copy()

print("Before")
print(f"a: {a}")
print(f"b: {b}\n")

b[0] = 100
print("After")
print(f"a: {a}")
print(f"b: {b}")

Before
a: [1 2 3]
b: [1 2 3]

After
a: [1 2 3]
b: [100   2   3]


### Mathematics

In [21]:
a = np.array([1, 2, 3, 4, 5])

print(f"Addition: {a + 2}")
print(f"Subtraction: {a - 2}")
print(f"Multiplication: {a * 2}")
print(f"Division: {a / 2}")
print(f"Modulo: {a % 2}")

Addition: [3 4 5 6 7]
Subtraction: [-1  0  1  2  3]
Multiplication: [ 2  4  6  8 10]
Division: [0.5 1.  1.5 2.  2.5]
Modulo: [1 0 1 0 1]


In [22]:
# Mathematical Operations on 2 arrays
a = np.array([2, 4, 6])
b = np.array([1, 3, 5])

print(f"Addition: {a + b}")
print(f"Subtraction: {a - b}")
print(f"Multiplication: {a * b}")
print(f"Division: {a / b}")
print(f"Modulo: {a % b}")

Addition: [ 3  7 11]
Subtraction: [1 1 1]
Multiplication: [ 2 12 30]
Division: [2.         1.33333333 1.2       ]
Modulo: [0 1 1]


In [23]:
print(f"Sin: {np.sin(a)}")
print(f"Cos: {np.cos(a)}")
print(f"Tan: {np.tan(a)}")

Sin: [ 0.90929743 -0.7568025  -0.2794155 ]
Cos: [-0.41614684 -0.65364362  0.96017029]
Tan: [-2.18503986  1.15782128 -0.29100619]


In [24]:
# Matrix Multiplication
a = np.ones((2, 3))
b = np.full((3, 2), 2)

print(f"a:{a}")
print(f"b:{b}")

print("a × b = \n")
print(np.matmul(a, b))

a:[[1. 1. 1.]
 [1. 1. 1.]]
b:[[2 2]
 [2 2]
 [2 2]]
a × b = 

[[6. 6.]
 [6. 6.]]


In [25]:
# Find determinant
mat = np.array([[1, 2], [3, 4]])
print(np.linalg.det(mat))

-2.0000000000000004


### Statistics

In [26]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [27]:
print(f"Min: {np.min(arr)}")
print(f"Max: {np.max(arr)}")
print(f"Mean: {np.mean(arr)}")
print(f"Standard Deviation: {np.std(arr)}")
print(f"Sum: {np.sum(arr)}")

Min: 1
Max: 6
Mean: 3.5
Standard Deviation: 1.707825127659933
Sum: 21


In [28]:
# Stats of specific rows/cols
print(f"Col: {np.min(arr, axis=0)}")
print(f"Row: {np.min(arr, axis=1)}")

Col: [1 2 3]
Row: [1 4]


### Reorganizing Arrays

In [29]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(a)
print(f"Shape of a: {a.shape}")

a_reshaped = a.reshape((8, 1))
print(a_reshaped)
print(f"Shape of a_reshaped: {a_reshaped.shape}")

[[1 2 3 4]
 [5 6 7 8]]
Shape of a: (2, 4)
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]
Shape of a_reshaped: (8, 1)


In [30]:
# Vertical Stacks

v1 = np.array([1, 2, 3, 4])
v2 = np.array([5, 6, 7, 8])

np.vstack([v1, v2, v2, v1, v1])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [1, 2, 3, 4]])

In [31]:
# Horizontal Stacks

v1 = np.ones((2, 4))
v2 = np.zeros((2, 2))

np.hstack([v1, v2])

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

In [32]:
# Concatenate Arrays

v1 = np.array([[1, 2, 3, 4]])
v2 = np.array([[5, 6, 7, 8]])

np.concatenate([v1, v2], axis=0)

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [33]:
# For 3D arrays
v1 = np.array([[[1, 2], [3, 4], [5, 6]], [[7, 8], [9, 10], [11, 12]]])
v2 = np.array([[[13, 14], [15, 16], [17, 18]], [[19, 20], [21, 22], [23, 24]]])

print(np.concatenate([v1, v2], axis=0))
print("===" * 10)
print(np.concatenate([v1, v2], axis=1))
print("===" * 10)
print(np.concatenate([v1, v2], axis=2))
print("===" * 10)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]

 [[13 14]
  [15 16]
  [17 18]]

 [[19 20]
  [21 22]
  [23 24]]]
[[[ 1  2]
  [ 3  4]
  [ 5  6]
  [13 14]
  [15 16]
  [17 18]]

 [[ 7  8]
  [ 9 10]
  [11 12]
  [19 20]
  [21 22]
  [23 24]]]
[[[ 1  2 13 14]
  [ 3  4 15 16]
  [ 5  6 17 18]]

 [[ 7  8 19 20]
  [ 9 10 21 22]
  [11 12 23 24]]]
